cmake_minimum_required(VERSION 2.8.3)

file(READ "${CMAKE_CURRENT_LIST_DIR}/../src/octree_raycast.cl" CL_PROGRAM)
file(WRITE "${CMAKE_CURRENT_LIST_DIR}/../src/octree_raycast.cl.h" "// Generated by octree_raycast_cl.cmake\n// from octree_raycast.cl\n#include <string>\n static const std::string OCTREE_RAYCAST_CL = R\"6a53dc5c(${CL_PROGRAM})6a53dc5c\";")
